import Footer from '@/components/Footer';
import Header from '@/components/Header';
import '@/styles/globals.css'

export const metadata = {
  title: 'Welcome to tecbiz-web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <Header />
      <body>{children}</body>
      <Footer />
    </div>
  );
}